version: '3'

services:
  db:
    image: mysql:8.0
    container_name: spring_boot_db
    environment:
      MYSQL_ROOT_PASSWORD: root@123456
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: admin@123456
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80