spring:
  datasource:
    url: jdbc:mysql://localhost:3307/app_db?createDatabaseIfNotExist=true&useSSL=false
    username: db_user
    password: admin@123456
    driverClassName: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: "classpath:com.java_spring_boot.core.repository/*.xml"
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    #    java:
    #      sql: DEBUG
    #    org:
    #      mybatis: DEBUG
    #      apache:
    #        ibatis: DEBUG
    com.java_spring_boot.core.repository: DEBUG
